FROM confluentinc/cp-zookeeper:latest

#RUN apt-get -y update && apt-get -y install curl
#RUN apt-get -y update && apt-get -y install netcat

#RUN apk update && apk add --no-cache curl 
#RUN apk update && apk add --no-cache netcat-openbsd 