# Using the Ubuntu image (our OS)
FROM bitnami/spark:3.5


USER root
# Add Dependencies for PySpark
RUN apt-get update && apt-get install -y \
        curl vim wget software-properties-common \
        bash ssh net-tools ca-certificates iputils-ping \
        python3 python3-pip

RUN pip3 install --upgrade pip

WORKDIR /opt/spark-app
COPY ./spark/run-spark-app.sh .
COPY ./spark/start-spark.sh .
COPY ./spark/sparkstreaming.py .
COPY ./spark/test01.py .
COPY ./spark/test02_stream.py .
COPY .env .
COPY requirements_spark.txt .

RUN chmod +x /opt/spark-app/*
RUN /opt/spark-app/start-spark.sh

RUN pip3 install --no-cache-dir -r requirements_spark.txt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
USER 1001
ENV PYTHONUNBUFFERED 1



WORKDIR /opt/bitnami/spark
CMD tail -f /tmp/java_opts.txt